apiVersion: v1
kind: Service
metadata:
  name: test-prometheus-service
spec:
  selector:
    app: test-prometheus-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30000
